projects:
  - id: ifmapcli
  - id: irond
  - id: irongui
  - id: visitmeta
  - id: ironloggui

files:
  - source: agendas/generated-agenda-seq.txt
    destination: /
  - source: agendas/ifmapcli-test.txt
    destination: /
  - source: agendas/generated-agenda-timed.txt
    destination: /
  - source: agendas/publish-update-example-agenda.txt
    destination: /
  - source: agendas/sme-user-logins.txt
    destination: /
  - source: agendas/module-starter-test.txt
    destination: /
  - source: irongui/irongui.properties
    destination: /irongui
