projects:
  - id: ifmapcli
  - id: irond
  - id: visitmeta
  - id: ironloggui

files:
  - source: agendas/rsa-2015.txt
  - source: agendas/rsa-2015-fallback.txt
  - source: agendas/rsa-2015-gpm.txt
  - source: agendas/rsa-2015-gpm-without-infrastructure.txt
  - source: agendas/rsa-2015-fallback-biggraph.txt
    destination: /
  - source: irond/publisher.properties
    destination: /irond
  - source: visitmeta/dataservice_connections.yml
    destination: visitmeta/config/
  - source: visitmeta/visualization_config.yml
    destination: visitmeta/config/
  - source: visitmeta/dataservice_config.yml
    destination: visitmeta/config/
