projects:
  - id: ifmapcli
  - id: irond
  - id: visitmeta
  - id: irongpm
  - id: ironloggui

files:
  - source: agendas/evaluation-scenario-2.txt
    destination: /
  - source: agendas/evaluation-scenario-2-without-breaks.txt
    destination: /
  - source: agendas/evaluation-scenario-2-with-manual-component-startup.txt
    destination: /
  - source: agendas/evaluation-scenario-2-automatic-and-stretched-timestamps.txt
    destination: /
  - source: irond/publisher.properties
    destination: irond
  - source: irond/basicauthusers.properties
    destination: irond
  - source: visitmeta/dataservice_connections.yml
    destination: visitmeta/config/
  - source: visitmeta/visualization_config.yml
    destination: visitmeta/config/
  - source: visitmeta/dataservice_config.yml
    destination: visitmeta/config/
  - source: irongpm/rules/scenario2-rules.jar
    destination: irongpm/rules/
  - source: irongpm/irongpm.yml
    destination: irongpm/
