projects:
  - id: ifmapcli
  - id: irond
  - id: visitmeta
  - id: ironloggui

files:
  - source: agendas/ext-ifmapcli.txt
    destination: /
  - source: irond/basicauthusers.properties
    destination: /irond
  - source: irond/ifmap.properties
    destination: /irond
  - source: irond/schema/simu.xsd
    destination: /irond/schema
  - source: xml/identifies-as.xml
    destination: /
  - source: xml/service-ip.xml
    destination: /
