projects:
  - id: ifmapcli
  - id: irond
  - id: visitmeta

files:
  - source: agendas/ics-security.txt
    destination: /
  - source: irond/basicauthusers.properties
    destination: /irond
  - source: irond/publisher.properties
    destination: /irond
  - source: visitmeta/dataservice_connections.yml
    destination: visitmeta/config/
  - source: visitmeta/visualization_config.yml
    destination: visitmeta/config/
  - source: visitmeta/dataservice_config.yml
    destination: visitmeta/config/
