projects:
  - id: ifmapcli
  - id: irond
  - id: irongui
  - id: visitmeta
  - id: ironloggui

files:
  - source: agendas/leuchtturm00.txt
    destination: /
  - source: agendas/leuchtturm01.txt
    destination: /
  - source: agendas/leuchtturm02.txt
    destination: /
  - source: agendas/leuchtturm03.txt
    destination: /
  - source: agendas/leuchtturm04.txt
    destination: /
  - source: agendas/leuchtturm05.txt
    destination: /
  - source: agendas/infrastructure_example.txt
    destination: /
  - source: agendas/example-agenda.txt
    destination: /
  - source: agendas/ncpvpn.txt
    destination: /
  - source: irond/infrastructure-metadata-2.1v1.xsd
    destination: /irond/schema
  - source: irond/infrastructure-identifier-2.1v1.xsd
    destination: /irond/schema
  - source: irond/basicauthusers.properties
    destination: /irond
  - source: irongui/irongui.properties
    destination: /irongui
