projects:
  - id: ifmapcli
  - id: irond
  - id: visitmeta
  - id: ironloggui

files:
  - source: agendas/visitmeta-project.txt
    destination: /
  - source: irond/basicauthusers.properties
    destination: /irond
  - source: irond/publisher.properties
    destination: /irond
  - source: visitmeta/config/dataservice_connections.yml
    destination: /visitmeta/config
  - source: visitmeta/config/visualization_config.yml
    destination: /visitmeta/config
