visualization:
  connection:
    # IF-MAP connection settings
    ifmap:
      # URL of the MAP server
      url: http://localhost:8443
      # username for basic authentication
      username: visitmeta-publisher
      # password for basic authentication
      password: visitmeta-publisher
      # Truststore configuration
      truststore:
        # path and filename of the keystore
        path: config/visitmeta.jks
        # password of the keystore
        password: visitmeta
      # connection uses a thread-safe SSRC
      threadsafe: true
      # initial connection timeout
      initialconnectiontimeout: 120000
    # irondetect connection settings
    irondetect:
      # URL of the irondetect REST service
      url: http://localhost:8001
    # additional connection to a VisITMeta dataservice
    dataservice:
      # URL of the VisITMeta dataservice REST service
      url: http://localhost:8000
      # Connection name that is used to retrieve JSON graph data
      connectionname: default
    dataservicessl:
      url: https://localhost:8445
      connectionname: defaultssl
      verifyhostname: false
  network:
    # The time interval (milliseconds) to request the dataservice for new changes.
    interval: 5000
  calculation:
    # The time interval (milliseconds) to recalculate the position of the nodes.
    interval: 500
    # Count of Iterations for the position calculation of the nodes.
    iterations: 100
    # Layout type on startup; possible values are:
    # FORCE_DIRECTED
    # SPRING
    # BIPARTITE
    # FORCE_DIRECTED_ALTERNATIVE
    # KAMADA_KAWAI
    layouttype: FORCE_DIRECTED
    # Sets JUNG layout algorithm related properties.
    jung:
      # Descriptions for force-directed layout settings from:
      # http://jung.sourceforge.net/doc/api/edu/uci/ics/jung/algorithms/layout/FRLayout.html
      forcedirected:
        # Sets how much edges try to keep their vertices together.
        attractionmultiplier: 0.75
        # Sets how much vertices try to push each other apart.
        repulsionmultiplier: 0.75
        # Sets the maximum number of iterations.
        maxiterations: 700
      # Descriptions for Spring layout settings from:
      # http://jung.sourceforge.net/doc/api/edu/uci/ics/jung/algorithms/layout/SpringLayout.html
      spring:
        # Sets the stretch parameter.
        # This value specifies how much the degrees of an edge's incident vertices should 
        # influence how easily the endpoints of that edge can move (that is, that edge's 
        # tendency to change its length).
        # The default value is 0.70. Positive values less than 1 cause high-degree 
        # vertices to move less than low-degree vertices, and values > 1 cause 
        # high-degree vertices to move more than low-degree vertices.
        # Negative values will have unpredictable and inconsistent results.
        stretch: 0.7
        # Sets the node repulsion range (in drawing area units).
        # Outside this range, nodes do not repel each other. The default value is 100.
        # Negative values are treated as their positive equivalents.
        repulsionrange: 100
        # Sets the force multiplier.
        # This value is used to specify how strongly an edge "wants" to be its default
        # length (higher values indicate a greater attraction for the default length),
        # which affects how much its endpoints move at each timestep. The default value
        # is 1/3. A value of 0 turns off any attempt by the layout to cause edges to
        # conform to the default length. Negative values cause long edges to get longer
        # and short edges to get shorter; use at your own risk.
        forcemultiplier: 0.33
      # Descriptions for Kamada-Kawai layout settings from:
      # http://jung.sourceforge.net/doc/api/edu/uci/ics/jung/algorithms/layout/KKLayout.html
      kamadakawai:
        # Shift all vertices so that the center of gravity is located at the center of
        # the screen.
        adjustforgravity: true
        # Sets a multiplicative factor that specifies the fraction of the graph's diameter
        # to be used as the inter-vertex distance between disconnected vertices.
        disconnecteddistancemultiplier: 2.0
        # Enable or disable the local minimum escape technique by exchanging vertices.
        exchangevertices: true
        # Sets a multiplicative factor which partly specifies the "preferred" length
        # of an edge (L).
        lengthfactor: 2.5
        # Sets the maximum number of iterations.
        maxiterations: 100
  highlights:
    # Timeout (milliseconds) to show the highlights for new and deleted nodes.
    timeout: 3000
  node:
    translation:
      # The animation time for the translation of a node to the new position.
      duration: 250
    information:
      # Sets the style for detailed node information when a node is selected
      # Possible values are:
      # XML_BREAKDOWN: breaks down the XML structure of nodes; the encapsulated XML
      #                of Extended Identifiers will be shown as a sub XML tree
      # PLAIN_XML:     a simple output of a nodes information, encapsulated XML
      #                will remain a single String
      style: XML_BREAKDOWN
  identifier:
    text:
      # Sets the text style for identifier nodes; possible values are:
      # SINGLE_LINE: a minimized style with all information in a single line
      # MULTI_LINE:  a more detailed style with possibly more information,
      #              using multiple lines
      # COMPACT:     a style that tries to use a single line, but will use
      #              additional lines when necessary and useful (for example
      #              for Extended Identifiers)
      style: POLICY_COMPACT
      # If true, the prefix 'extended identifier: ' is shown before the actual name of an extended identifier.
      # This is not supported by all styles. 
      showextendedidentifierprefix: false
    node:
      # Sets the geometric style of identifier nodes; possible values are:
      # RECTANGLES_WITH_ROUNDED_CORNERS
      # RECTANGLES_WITH_RECTANGULAR_CORNERS
      # ELLIPSE
      # EXAMPLE (shows how different types of identifier/metadata can be rendered differently)
      style: RECTANGLES_WITH_ROUNDED_CORNERS
  metadata:
    text:
      # Sets the text style for metadata nodes; possible values are:
      # SINGLE_LINE:    just the typename of the metadata is used
      # WITH_TIMESTAMP: adds a line with the publisher timestamp to the typename
      # COMPACT:        further information on additional lines
      style: POLICY_COMPACT
    node:
      # Sets the geometric style of identifier nodes; possible values are:
      # RECTANGLES_WITH_ROUNDED_CORNERS
      # RECTANGLES_WITH_RECTANGULAR_CORNERS
      # ELLIPSE
      # EXAMPLE (shows how different types of identifier/metadata can be rendered differently)
      style: RECTANGLES_WITH_RECTANGULAR_CORNERS
  edge:
    # Sets the style of edges; possible values are:
    # STRAIGHT_LINE
    # STRAIGHT_DASHED_LINE
    # ORTHOGONAL_LINE
    # CURVED_LINE
    # EXAMPLE (shows how different types of identifier/metadata can be rendered differently)
    style: POLICY
  history:
    navigation:
      # Sets the control mechanism for history navigation; possible values are:
      # TAB_BASED_NAVIGATION:          uses multiple tabs to switch between
      #                                live view, history view and delta view
      # RANGE_SLIDER_BASED_NAVIGATION: uses a slider with two knobs that
      #                                includes all possible modes
      style: TAB_BASED_NAVIGATION
  searchandfilter:
    # Sets the search and filtering mechanism; possible values are:
    # SIMPLE_SEARCH_AND_NO_FILTER: a simple search functionality, using a single textfield
    #                              and matches every node containing the given 
    #                              input string
    style: SIMPLE_SEARCH_AND_NO_FILTER
    # value in 0.0 to 1.0 for transparency of elements that do not match a search value
    transparency : 0.2
      
guicontroller:
  zfactor: 0.03
  xyfactor: 20.0

window:
  width: 1280
  height: 720
  divider: 170
  position:
    x: 0
    y: 0

color:
  background: '0xFFFFFF'
  edge: '0x000000'
  metadata:
    text: '0x000000'
    inside: '0xFF9966'
    outside: '0xFF9966'
    border: '0x000000'
  node:
    new: '0x266E62'
    delete: '0xA73946'
    selected: '0xCEB100'
    search: '0x88A538'
    mouseover: '0x708090'
    blank: '0xFFFFFF'
    highlight:
      value: '0xFF0000'
      typenames: policy-action,policy-feature,policy-evaluation,policy-partial-result,pattern-matched,event,unexpected-behavior,attack-detected
  identifier:
    access-request:
      text: '0x000000'
      inside: '0x9999FF'
      outside: '0x9999FF'
      border: '0x000000'
    device:
      text: '0x000000'
      inside: '0x9999FF'
      outside: '0x9999FF'
      border: '0x000000'
    identity:
      text: '0x000000'
      inside: '0x9999FF'
      outside: '0x9999FF'
      border: '0x000000'
    ip-address:
      text: '0x000000'
      inside: '0x9999FF'
      outside: '0x9999FF'
      border: '0x000000'
    mac-address:
      text: '0x000000'
      inside: '0x9999FF'
      outside: '0x9999FF'
      border: '0x000000'
    extended:
      text: '0x000000'
      inside: '0x9999FF'
      outside: '0x9999FF'
      border: '0x000000'
  ironvas-b1c809e2-281d-4b33-a354-853c2f330f13:
    inside: '0xff3300'
    outside: '0xff3300'
  ironnmap-b3c9d2fe-00d9-47ef-9701-5ffe51a4dab4:
    inside: '0xffcc00'
    outside: '0xffcc00'
  decomap-openvpn-5580e5d4-1877-4fb3-8daa-0ff12e9881c4:
    inside: '0xffcc00'
    outside: '0xffcc00'   
  irongenlog-freeradius-d240c2ae-1223-4dfa-acf9-7002f9227be7:
    inside: '0xF7F4AD'
    outside: '0xF7F4AD'
  decomap-snort-fce9a8e2-8e99-4530-ada7-ad89dd485a9a:
    inside: '0x00cc00'
    outside: '0x00cc00'
  decomap-iptables-2d3ae3f8-ce8f-4a10-974d-bc5fa178a37e:
    inside: '0x789078'
    outside: '0x789078'
  irondhcp-34a72835-040d-4332-a261-1d37aaa2f357:
    inside: '0xF7C2AB'
    outside: '0xF7C2AB'
  irongpm-1d3206d1-11f1-4649-b9df-9b1cb3319052:
    inside: '0xD1686D'
    outside: '0xD1686D'
  irondetect-2c15759e-7958-47cf-a8cf-8336d8c7adb6:
    inside: '0xD1686D'
    outside: '0xD1686D'
  irondetect-pdp-0cbfcbf5-a9a8-42ff-85e1-c2e0643002c8:
    inside: '0xD1686D'
    outside: '0xD1686D'
  irondetect-publisher-bb5955ce-d0b2-4b0b-b396-c36c07380427:
    inside: '0xD1686D'
    outside: '0xD1686D'
  visitmeta-publisher-19dcb7ac-ad5b-4a8e-835e-d9c2528ab67c:
    inside: '0xD1686D'
    outside: '0xD1686D'
